version: '3.9'

x-common-variables: &common-variables
  NODE_ENV: "production"
  API_PORT: "31339"
  GRAPE_APH: "30001"
  GRAPE_HOST: "grape1"

services:
  grape1:
    container_name: grape1
    build:
      context: .
      dockerfile: Dockerfile.grenache-grape
    restart: always
    networks:
      - grapes
    environment:
      <<: *common-variables
      GRAPE_DP: "20001"
      GRAPE_BN: "20002"
      GRAPE_BIND: "grape2"

  grape2:
    container_name: grape2
    build:
      context: .
      dockerfile: Dockerfile.grenache-grape
    restart: always
    depends_on:
      - grape1
    networks:
      - grapes
    environment:
      <<: *common-variables
      GRAPE_DP: "20002"
      GRAPE_APH: "40001"
      GRAPE_BN: "20001"
      GRAPE_BIND: "grape1"

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: always
    depends_on:
      - grape1
      - grape2
    networks:
      - grapes
    volumes:
      - temp:/home/node/bfx-reports-framework/temp
      - ./db:/home/node/bfx-reports-framework/db
      - ./csv:/home/node/bfx-reports-framework/csv
      - ./logs:/home/node/bfx-reports-framework/logs
    environment:
      <<: *common-variables
      WORKER_API_PORT: "1337"
      WORKER_WS_PORT: "1455"
      TEMP_FOLDER: "/home/node/bfx-reports-framework/temp"
      DB_FOLDER: "/home/node/bfx-reports-framework/db"
      CSV_FOLDER: "/home/node/bfx-reports-framework/csv"
      LOGS_FOLDER: "/home/node/bfx-reports-framework/logs"
      SECRET_KEY: ${SECRET_KEY} # Required
      SCHEDULER_RULE: ${SCHEDULER_RULE} # Non-required

  express:
    container_name: express
    build:
      context: .
      dockerfile: Dockerfile.express
    restart: always
    depends_on:
      - worker
      - grape1
      - grape2
    networks:
      - grapes
    ports:
      - "127.0.0.1:31339:31339"
    volumes:
      - ./logs:/home/node/bfx-report-express/logs
    environment:
      <<: *common-variables

networks:
  grapes:
    driver: bridge

volumes:
  temp:
